Send an SMS message if the account doesn't have a verified email address
Sage-Bionetworks/BridgeUserDataDownloadService pull request #22
Opened 2018-04-18 23:38 UTC by alxdarksage

2018-04-19 21:13 UTC, DwayneJengSage requested changes

2018-04-19 21:13 UTC, DwayneJengSage commented on pom.xml
>      <properties>
Also need to bump package version, so that the worker can consume the new version

2018-04-19 21:13 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/udd/accounts/BridgeHelper.java
> +        }
If the user has neither an email address nor a phone, this will throw, and the SQS queue will cycle the request several times before giving up. It would be better to add an else clause and throw a PollSqsWorkerBadRequestException.

2018-04-19 21:13 UTC, DwayneJengSage commented on src/main/java/org/sagebionetworks/bridge/udd/helper/SnsHelper.java
> +    public static final String SMS_TYPE_TRANSACTIONAL = "Transactional";
Do we want to call SNS directly? Or do we want to call the Bridge API for sending SNS? The latter might be better for not having so much duplicate code.

2018-04-19 21:13 UTC, DwayneJengSage commented on src/test/java/org/sagebionetworks/bridge/udd/worker/BridgeUddProcessorTest.java
> +        when(mockBridgeHelper.getAccountInfo(STUDY_ID, USER_ID)).thenReturn(accountInfo);
Unit test for the no data case?

2018-04-20 17:04 UTC, alxdarksage commented on src/main/java/org/sagebionetworks/bridge/udd/accounts/BridgeHelper.java
> +        }
Adde else clause with test.

2018-04-20 17:24 UTC, alxdarksage commented on src/test/java/org/sagebionetworks/bridge/udd/worker/BridgeUddProcessorTest.java
> +        when(mockBridgeHelper.getAccountInfo(STUDY_ID, USER_ID)).thenReturn(accountInfo);
Added

2018-04-20 22:17 UTC, DwayneJengSage approved these changes

2018-04-23 16:36 UTC, merged